name: scrape

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *'   # daily 09:00 UTC

# ✅ give this workflow write access to push the CSV
permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Show files (debug)
        run: ls -la

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        env:
          USER_AGENT: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123 Safari/537.36
        run: |
          python scraper.py
          echo "---- CSV head ----"
          head -n 5 products.csv || true

      - name: Commit CSV to repo
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update scraped products.csv"
          file_pattern: products.csv

      # ♻️ Always upload the CSV even if commit step fails
      - name: Upload products.csv artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: products
          path: products.csv
          if-no-files-found: warn
