name: scrape

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * *"   # daily 09:00 UTC

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        env:
          USER_AGENT: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123 Safari/537.36
          NS_COOKIE: ${{ secrets.NS_COOKIE }}
          EMERSON_COOKIE: ${{ secrets.EMERSON_COOKIE }}
        run: python scraper.py

      - name: Commit products.csv
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update scraped products.csv"
          file_pattern: products.csv

      - name: Upload products.csv artifact
        uses: actions/upload-artifact@v4
        with:
          name: products
          path: products.csv
          if-no-files-found: warn
