name: scrape
on:
  schedule:
    - cron: "0 5 * * *"   # daily at 05:00 UTC
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - run: pip install -r requirements.txt
      - run: python scraper.py

      - name: Commit & push CSV
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add products.csv
          git commit -m "Daily scrape: $(date -u +%F)" || echo "No changes to commit"
          git push
